Repository tektoncd/community, pull requests merged in 2019-11, with the labels that each got.

#45 Update boskos access docs
  governance.md
Labels: approved, lgtm, size/S

#46 Add a peribolos configuration and documentation on how to use it.
  README.md
  org/README.md
  org/org.yaml
Labels: approved, lgtm, size/M

#48 Add ameyer-pivotal to the tektoncd org!
  org/org.yaml
Labels: approved, lgtm, size/XS

#49 Add sclevine to the tekton org!
  org/org.yaml
Labels: approved, lgtm, size/XS

#50 Add remaining buildpack owners to the tekton org.
  org/org.yaml
Labels: approved, lgtm, size/L

#52 Re-remove knative-prow-robot and fix pradeepitm12.
  org/org.yaml
Labels: approved, lgtm, size/XS

#51 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#55 Add user profiles link to front page 🎩
  README.md
Labels: approved, lgtm, size/XS

#54 Add arilivigni to members of the org
  org/org.yaml
Labels: approved, lgtm, size/XS

#56 Add spomorski@ to the tektoncd org
  org/org.yaml
Labels: approved, lgtm, size/XS

#57 Add @raffamendes to the tekton org
  org/org.yaml
Labels: approved, lgtm, size/XS

#58 Add @praveen4g0 to the tekton org
  org/org.yaml
Labels: approved, lgtm, size/XS
