Repository tektoncd/community, pull requests merged in 2019-09, with the labels that each got.

#35 Add link to beta working group meetings + agenda β
  README.md
  contact.md
Labels: approved, lgtm, size/M

#36 More clearly document doc visibility
  contact.md
Labels: approved, lgtm, size/S

#37 Move triggers WG to Tuesdays ⚡
  contact.md
Labels: approved, lgtm, size/XS
