Repository tektoncd/community, pull requests merged in 2019-04, with the labels that each got.

#7 Add the initial bootstrap governance proposal.
  governance.md
Labels: approved, lgtm, size/M

#8 Fix typos in initial governance.
  governance.md
Labels: approved, lgtm, size/XS

#9 Add CONTRIBUTING guidelines for all tektoncd projects ✔️
  CONTRIBUTING.md
  OWNERS
  README.md
  contact.md
  governance.md
  process.md
  standards.md
Labels: approved, lgtm, size/L

#11 Fix link typo for standard[s]
  README.md
Labels: approved, lgtm, size/XS

#12 Add guidelines for new project creation 🎂
  README.md
  process.md
Labels: approved, lgtm, size/M

#14 Create Tekton mailing list for code of conduct issues
  code-of-conduct.md
  governance.md
Labels: approved, lgtm, size/XS

#15 Document permissions that governing board members should get ⚖️
  governance.md
Labels: approved, lgtm, size/S

#16 Update link to use `tektoncd` slack! 🗣️
  contact.md
Labels: approved, lgtm, size/XS

#17 Add the invite link to the slack 👼
  contact.md
Labels: approved, lgtm, size/XS
