Repository tektoncd/community, pull requests merged in 2020-08, with the labels that each got.

#159 TEP-0007: Conditions Beta
  teps/0007-conditions-beta.md
Labels: approved, lgtm, size/XL

#165 Format Conditions Beta TEP
  teps/0007-conditions-beta.md
Labels: approved, lgtm, size/M

#166 Add Max to the org
  org/org.yaml
Labels: approved, lgtm, size/XS

#167 TEP-0007: Conditions Beta - further discussion and status update
  teps/0007-conditions-beta.md
Labels: approved, lgtm, size/XS

#168 org: remove faulty line…
  org/org.yaml
Labels: approved, lgtm, size/XS

#174 Update catalog facilitators
  working-groups.md
Labels: approved, lgtm, size/S

#173 Small TEP fixes 👼
  teps/0003-tekton-catalog-organization.md
  teps/0004-task-results-in-final-tasks.md
  teps/0005-tekton-oci-bundles.md
  teps/0007-conditions-beta.md
Labels: approved, lgtm, size/L

#176 org: khrm maintainer of triggers
  org/org.yaml
Labels: approved, lgtm, size/XS

#175 Move catalog organization TEP to implementable
  teps/0003-tekton-catalog-organization.md
Labels: approved, lgtm, size/XS

#180 TEP-0007: Fix headings
  teps/0007-conditions-beta.md
Labels: approved, lgtm, size/S

#181 Adding Yawen Luo into membership
  org/org.yaml
Labels: approved, lgtm, size/XS

#148 TEP-0009: Trigger CRD
  teps/0009-trigger-crd.md
Labels: approved, lgtm, size/L

#162 TEP-0008: Support Knative Service for Triggers EventListener Pod
  teps/0008-support-knative-service-for-triggers-eventlistener-pod.md
Labels: approved, lgtm, size/L

#172 TEP-0012: API Spec
  teps/0012-api-spec.md
Labels: approved, kind/tep, lgtm, size/L

#187 org: update plumbing maintainers team ⛺️
  org/org.yaml
Labels: approved, lgtm, size/XS

#169 TEP-0010 Propose optional workspaces feature
  teps/0010-optional-workspaces.md
Labels: approved, kind/tep, lgtm, size/L

#193 Make the deprecation of Conditions CRD more prominent in the TEP
  teps/0007-conditions-beta.md
Labels: approved, lgtm, size/XS
