Repository tektoncd/community, pull requests merged in 2020-05, with the labels that each got.

#100 Update docs on review process to reflect current behaviour
  process.md
Labels: approved, lgtm, size/XS

#102 Updated Documentation working group
  working-groups.md
Labels: approved, lgtm, size/XS

#103 Add catalog + hub working group 📰
  working-groups.md
Labels: approved, lgtm, size/S

#104 Add link to the dashboard roadmap
  roadmap.md
Labels: approved, lgtm, size/XS

#105 Add cli Roadmap Link
  roadmap.md
Labels: approved, lgtm, size/XS

#106 Add Jonas to the org
  org/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#108 Add the Jason and Andrea as OWNERS to community
  OWNERS
Labels: approved, lgtm, size/XS

#112 add myself as a member to the Tekton org.
  org/org.yaml
Labels: approved, lgtm, size/XS

#109 Add Meixing into the member list
  org/org.yaml
Labels: approved, lgtm, size/XS

#111 Add yuege01(Ziwei Fang) to Tekton Org
  org/org.yaml
Labels: approved, lgtm, size/XS

#114 Add myself and @n3wscott
  org/org.yaml
Labels: approved, lgtm, size/XS
