Repository tektoncd/community, pull requests merged in 2020-04, with the labels that each got.

#92 Add tektoncd/hub owners to the org 🤺
  org/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#77 Create 2020 roadmap 🛣️
  README.md
  roadmap.md
Labels: approved, cla: yes, lgtm, size/M

#93 Beta working group has morphed into the API working group 🦸‍♀️
  working-groups.md
Labels: approved, cla: yes, lgtm, size/S

#94 Update facilitator lists 📝
  working-groups.md
Labels: approved, cla: yes, lgtm, size/XS

#95 Add jerop to the org
  org/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#97 Add eddycharly to the org
  org/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#98 Add info about EasyCLA 👩‍⚖️
  README.md
  process.md
Labels: approved, cla: yes, lgtm, size/S

#99 Fix docs about peribolos
  org/README.md
Labels: approved, cla: yes, lgtm, size/XS
