Repository tektoncd/community, pull requests merged in 2020-10, with the labels that each got.

#211 TEP-0019: Add other architecture support
  teps/0019-other-arch-support.md
Labels: approved, kind/tep, lgtm, size/L

#221 Move TEP-0014 Step timeouts to implementable
  teps/0014-step-timeout.md
Labels: approved, kind/tep, lgtm, size/S

#226 Add GregDritschler to the org
  org/org.yaml
Labels: approved, lgtm, size/XS

#224 Add TEP-0024: Embedded Trigger Templates
  teps/0024-embedded-trigger-templates.md
Labels: approved, kind/tep, lgtm, size/L

#204 Draft Hermekton TEP
  teps/0024-hermekton.md
Labels: approved, kind/tep, lgtm, size/L

#197 Update governance.md
  governance.md
Labels: approved, lgtm, size/L

#230 teps: Update TOC by running ./hack/update-toc.sh
  teps/0016-concise-trigger-bindings.md
  teps/0019-other-arch-support.md
  teps/0024-hermekton.md
Labels: approved, kind/misc, lgtm, size/M

#231 Update hermekton TEP number to 0025
  teps/0025-hermekton.md
Labels: approved, lgtm, size/XS

#196 Add Hacktoberfest 2020 guidance from cdf
  README.md
  hacktoberfest-2020.md
Labels: approved, lgtm, size/M

#233 Move optional workspaces to 'implemented' state
  teps/0010-optional-workspaces.md
Labels: approved, lgtm, size/XS

#212 TEP-0020: Add s390x architecture support
  teps/0020-s390x-support.md
  teps/images/0020-diagram.png
Labels: approved, kind/tep, lgtm, size/L

#238 Clarify TEP Requirements Section
  teps/NNNN-tep-template/README.md
Labels: approved, kind/cleanup, lgtm, size/XS

#237 TEP-0027: HTTPS Connection To Triggers EventListener
  teps/0027-https-connection-to-triggers-eventlistener.md
Labels: approved, kind/tep, lgtm, size/L

#242 Add MacStadium contributors to Tekton org
  org/org.yaml
Labels: approved, lgtm, size/XS

#243 Add jinchihe as memeber
  org/org.yaml
Labels: approved, lgtm, size/XS
