Repository tektoncd/community, pull requests merged in 2020-09, with the labels that each got.

#146 TEP-0006: New (sub-)metrics
  teps/0006-tekton-metrics.md
Labels: approved, kind/tep, lgtm, size/L

#186 Changed Knative Triggers TEP Status to Implementable and addressed few open points
  teps/0008-support-knative-service-for-triggers-eventlistener-pod.md
Labels: approved, kind/tep, lgtm, size/M

#195 Add Khurram Baig khrm to tep/OWNERS
  teps/OWNERS
Labels: approved, lgtm, size/XS

#185 working-groups: update table of facilitators
  working-groups.md
Labels: approved, lgtm, size/M

#189 Add Yumeng to the org
  org/org.yaml
Labels: approved, lgtm, size/XS

#194 Some minor fixes for typos/grammer for trigger-crd TEP
  teps/0009-trigger-crd.md
Labels: approved, lgtm, size/L

#184 Changing the Triggers CRD TEP Status to Implementable
  teps/0009-trigger-crd.md
Labels: approved, kind/tep, lgtm, size/M

#200 Added khalkie to Tekton Organization
  org/org.yaml
Labels: approved, lgtm, size/XS

#202 Add NavidZ to the org
  org/org.yaml
Labels: approved, lgtm, size/XS

#201 TEP-0014 presents the Step timeout feature
  teps/0014-step-timeout.md
Labels: approved, lgtm, size/L

#183 Add Ziheng to the org
  org/org.yaml
Labels: approved, lgtm, size/XS

#199 Move optional workspaces TEP to implementable
  teps/0010-optional-workspaces.md
Labels: approved, lgtm, size/XS

#207 Fix toc in a couple of teps
  teps/0008-support-knative-service-for-triggers-eventlistener-pod.md
  teps/0014-step-timeout.md
Labels: approved, kind/cleanup, lgtm, size/S

#192 TEP-0007: Add When Expressions Status
  teps/0007-conditions-beta.md
Labels: approved, kind/tep, lgtm, size/L

#213 Remove WhenExpressions names
  teps/0007-conditions-beta.md
Labels: approved, lgtm, size/S

#206 TEP-0016: Concise Embedded TriggerBindings
  teps/0016-concise-trigger-bindings.md
Labels: approved, kind/tep, lgtm, size/L

#205 TEP-0005: Make Tekton Bundles implementable
  teps/0005-tekton-oci-bundles.md
Labels: approved, kind/tep, lgtm, size/M

#215 Add xinruzhang to org
  org/org.yaml
Labels: approved, lgtm, size/XS

#214 Add FogDong to the org
  org/org.yaml
Labels: approved, lgtm, size/XS

#216 add Peaorl to org
  org/org.yaml
Labels: approved, lgtm, size/XS

#219 Add barthy1 to the org
  org/org.yaml
Labels: approved, lgtm, size/XS

#171 Add Tekton Design Principles
  design-principles.md
Labels: approved, lgtm, size/S
