Repository tektoncd/community, pull requests merged in 2020-01, with the labels that each got.

#64 Fix the broken link of general community meeting VC
  working-groups.md
Labels: approved, cla: yes, lgtm, size/XS

#63 Add kimholmes
  org/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#65 Update org.yaml
  org/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#66 Add othomann as a new member
  org/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#60 Lowercase w for VMware
  working-groups.md
Labels: approved, lgtm, size/XS

#31 Add documentation on how governance decisions are communicated.
  governance.md
Labels: approved, cla: yes, lgtm, size/XS

#70 Add Asia friendly general working group meeting 🌏
  working-groups.md
Labels: approved, cla: yes, lgtm, size/M

#71 Fix Typo
  working-groups.md
Labels: approved, cla: yes, lgtm, size/XS

#72 Triggers meeting is now every week! ⚡
  working-groups.md
Labels: approved, cla: yes, lgtm, size/XS

#74 Move working group to 1:00pm EST on thursdays 📅
  working-groups.md
Labels: approved, cla: yes, lgtm, size/XS

#73 Fix calendar links for documentation and cli 📅
  working-groups.md
Labels: approved, cla: yes, lgtm, size/XS
