Repository tektoncd/community, pull requests merged in 2020-11, with the labels that each got.

#241 Add design evaluation based on design principles to TEP template
  design-principles.md
  teps/NNNN-tep-template/README.md
Labels: approved, lgtm, size/S

#182 TEP-0011: Redirecting Step Output Streams
  teps/0011-redirecting-step-output-streams.md
Labels: approved, kind/tep, lgtm, size/L

#246 TEP-0007: Conditions Beta Skipping
  teps/0007-conditions-beta.md
Labels: approved, kind/tep, lgtm, size/S

#234 Adding TEP for accessing task execution status at runtime
  teps/0028-task-execution-status-at-runtime.md
Labels: approved, kind/tep, lgtm, size/L

#247 Add design principles to the main README
  README.md
Labels: approved, kind/misc, lgtm, size/XS

#133 Add contributor and reviewer expectations
  standards.md
Labels: approved, kind/documentation, lgtm, size/L

#236 Mark the Hermekton TEP as implementable.
  teps/0025-hermekton.md
Labels: approved, lgtm, size/XS

#248 Create teams of collaborators
  .gitignore
  org/README.md
  org/collaborator.py
  org/org.yaml
  org/requirements.txt
Labels: approved, lgtm, size/XL

#218 TEP-0022: Triggers - Immutable Input Events
  teps/0022-trigger-immutable-input.md
Labels: approved, kind/tep, lgtm, size/L

#251 Remove lucperkins from website maintainers
  org/org.yaml
Labels: approved, lgtm, size/XS

#179 Add notes about TEP numbers
  hack/tep-number.sh
  teps/README.md
Labels: approved, lgtm, size/M

#250 Adds conditions on bumping the resource version based on bumped image
  teps/0003-tekton-catalog-organization.md
Labels: approved, lgtm, size/XS

#225 TEP: Step and Sidecar Workspaces
  teps/XXXX-step-workspaces.md
Labels: approved, kind/tep, lgtm, size/L

#252 Update the TEP table
  hack/teps.py
  teps/README.md
Labels: approved, kind/documentation, lgtm, size/S

#235 TEP: Workspace Paths
  teps/XXXX-workspace-paths.md
Labels: approved, kind/tep, lgtm, size/L

#253 Fix collaborators groups
  org/collaborator.py
  org/org.yaml
Labels: approved, lgtm, size/L

#229 TEP-0026- Add TEP for interceptor plugins
  teps/0026-interceptor-plugins.md
Labels: approved, kind/tep, lgtm, size/XL

#203 TEP-0015 - Add a pending setting to Tekton PipelineRun and TaskRuns
  teps/0015-pending-pipeline.md
Labels: approved, kind/tep, lgtm, size/L

#257 Add Design Evaluation to TEP template table of contents
  teps/NNNN-tep-template/README.md
Labels: approved, lgtm, size/XS

#255 Set default project permission to "none"
  org/org.yaml
Labels: approved, kind/misc, lgtm, size/XS

#261 Mark TEP-0016 and TEP-0024 as implemented.
  teps/0016-concise-trigger-bindings.md
  teps/0024-embedded-trigger-templates.md
Labels: approved, lgtm, size/XS

#264 triggers: update WG meeting time
  working-groups.md
Labels: approved, lgtm, size/XS

#217 TEP-0021: Results API
  teps/0021-results-api.md
Labels: approved, kind/tep, lgtm, size/XL

#263 Add a renumber command to the teps tool
  teps/README.md.mustache
  teps/tools/Dockerfile
  teps/tools/README.md
  teps/tools/requirements.txt
  teps/tools/tep-template.md.template
  teps/tools/teps.py
Labels: approved, lgtm, size/L

#262 Update immutable input events to implementable
  teps/0022-trigger-immutable-input.md
Labels: approved, kind/tep, lgtm, size/XS

#269 Add myself to experimental.collaborators
  org/org.yaml
Labels: approved, lgtm, size/XS

#267 Fix the docker file and teps_folder for CI runs
  teps/0021-results-api.md
  teps/README.md
  teps/README.md.mustache
  teps/tools/Dockerfile
  teps/tools/teps.py
Labels: approved, lgtm, size/M

#268 Add a Use Cases sub-section to Motivations in the TEP template
  teps/tools/tep-template.md.template
Labels: approved, lgtm, size/S

#270 Remove the User Stories section from the TEP template
  teps/tools/tep-template.md.template
Labels: approved, lgtm, size/S

#244 Change status of TEP-0027 to Implementable
  teps/0027-https-connection-to-triggers-eventlistener.md
Labels: approved, kind/tep, lgtm, size/M

#272 Add installation instruction to the teps tool README
  teps/tools/README.md
Labels: approved, lgtm, size/S

#278 Fix TEP table
  teps/README.md
Labels: approved, lgtm, size/XS

#254 TEP 0004- task results in finally - updating proposal
  teps/0004-task-results-in-final-tasks.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/M

#265 TEP-0021 Result API: Record Subresources
  teps/0021-results-api.md
Labels: approved, kind/tep, lgtm, size/M

#282 Make title argument as required
  teps/tools/teps.py
Labels: approved, lgtm, size/XS

#283 Label -> Annotation in Deprecation Strategy in TEP-0003
  teps/0003-tekton-catalog-organization.md
Labels: approved, lgtm, size/XS

#284 Adds Piyush and Vinamra as the members of the hub
  org/org.yaml
Labels: approved, lgtm, size/XS

#275 TEP-0032 Tekton notifications
  teps/0020-s390x-support.md
  teps/0026-interceptor-plugins.md
  teps/0027-https-connection-to-triggers-eventlistener.md
  teps/0029-step-workspaces.md
  teps/0032-tekton-notifications.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L
