Repository tektoncd/community, pull requests merged in 2020-12, with the labels that each got.

#281 TEP-0021 Results API: Mark TEP as implementable.
  teps/0021-results-api.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/XS

#287 Add rhuss to tektoncd org members
  org/org.yaml
Labels: approved, lgtm, size/XS

#289 [results] Create initial peribolos config.
  org/org.yaml
Labels: approved, lgtm, size/M

#291 org: add savita and pradeep to operator collaborators
  org/org.yaml
Labels: approved, lgtm, size/XS

#292 Individuals cannot be both team maintainers and members
  org/org.yaml
Labels: approved, lgtm, size/XS

#293 Sync Pipeline OWNERS with org.yaml
  org/org.yaml
Labels: approved, lgtm, size/XS

#295 Add tektoncd/results to simple OWNER requirements list.
  process.md
Labels: approved, lgtm, size/XS

#152 TEP-0035: add tep for further documenting how-to's around policy, authentication, authorization, RBAC, and Tekton
  teps/0035-document-tekton-position-around-policy-authentication-authorization.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/XL
