Repository tektoncd/community, pull requests merged in 2020-07, with the labels that each got.

#139 add psschwei as an org member
  org/org.yaml
Labels: approved, lgtm, size/XS

#140 Admins can't be members 😛
  org/org.yaml
Labels: approved, lgtm

#128 TEP 0002: Custom Tasks
  teps/0002-custom-tasks.md
Labels: approved, lgtm, size/L

#142 Update to the TEP workflow
  teps/0001-tekton-enhancement-proposal-process.md
Labels: approved, lgtm, size/S

#143 Mark TEP 0002 as implementable
  teps/0002-custom-tasks.md
Labels: approved, lgtm, size/S

#123 TEP 0003: Tekton Catalog Organization
  teps/0003-tekton-catalog-organization.md
Labels: approved, lgtm, size/XL

#149 Two tiny edits to TEP-003
  teps/0003-tekton-catalog-organization.md
Labels: approved, lgtm, size/XS

#150 Add jonjohnsonjr as an org member
  org/org.yaml
Labels: approved, lgtm, size/XS

#151 adding priti as a facilitator to General WG
  working-groups.md
Labels: approved, lgtm, size/XS

#155 Adds an example in catalog reorg TEP
  teps/0003-tekton-catalog-organization.md
Labels: approved, lgtm, size/M

#157 org: maintain tektoncd teams using peribolos
  org/org.yaml
Labels: approved, lgtm, size/L

#153 Adding TEP for task results in final tasks
  teps/0004-task-results-in-final-tasks.md
Labels: approved, lgtm, size/L

#158 adding references section to TEP template
  teps/NNNN-tep-template/README.md
Labels: approved, lgtm, size/XS

#160 explaining how to add images
  teps/NNNN-tep-template/README.md
Labels: approved, lgtm, size/XS

#161 changing the status to implementable
  teps/0004-task-results-in-final-tasks.md
Labels: approved, lgtm, size/M

#163 Update Triggers WG facilitators
  working-groups.md
Labels: approved, lgtm, size/S

#137 TEP-0005: Tekton OCI Bundle
  teps/0005-tekton-oci-bundles.md
Labels: approved, lgtm, size/L
