Repository tektoncd/community, pull requests merged in 2020-06, with the labels that each got.

#115 Adding myself to be official
  org/org.yaml
Labels: approved, lgtm, size/XS

#116 Add Florian to the org, to own the `helm` task.
  org/org.yaml
Labels: approved, lgtm, size/XS

#117 Adding Operator & Deployment Working Group
  working-groups.md
Labels: approved, lgtm, size/S

#119 Update working-groups.md workgroups list
  working-groups.md
Labels: approved, lgtm, size/XS

#120 Add YolandaDu1997 to org
  org/org.yaml
Labels: approved, lgtm, size/XS

#122 Minor nit updates to TEP doc for typos and grammar
  teps/0001-tekton-enhancement-proposal-process.md
Labels: approved, lgtm, size/M

#124 Add lukehinds, mpeters and font to the org!
  org/org.yaml
Labels: approved, lgtm, size/XS

#132 Add maneeshmehra as an org member, to own "buildid" task
  org/org.yaml
Labels: approved, lgtm, size/XS

#131 Add UX and performance as optional sections in TEPs
  teps/NNNN-tep-template/README.md
Labels: approved, lgtm, size/S

#134 Add vinamra28 as an org member
  org/org.yaml
Labels: approved, lgtm, size/XS

#135 Add divyansh42 to Tekton org
  org/org.yaml
Labels: approved, lgtm, size/XS

#136 TEP: fix template table of content 🙃
  teps/NNNN-tep-template/README.md
Labels: approved, lgtm, size/XS

#126 add skelterjohn to org members
  org/org.yaml
Labels: approved, lgtm, size/XS

#130 Add governance member as owners on the org
  org/org.yaml
Labels: approved, lgtm, size/XS
