Repository tektoncd/community, pull requests merged in 2021-03, with the labels that each got.

#365 Requesting access to tektoncd org as member
  org/org.yaml
Labels: approved, lgtm, size/XS

#360 Fix link to add permissions script 🔗
  governance.md
Labels: approved, kind/cleanup, lgtm, size/XS

#345 Nested Triggers proposal
  teps/0053-nested-triggers.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#337 Update dashboard reference from master to main 🧙
  roadmap.md
Labels: approved, kind/misc, lgtm, size/XS

#363 Add TEP review SLOs 👩‍⚖️
  teps/README.md
  teps/README.md.mustache
Labels: approved, lgtm, size/M

#342 TEP-0050 - ignore task failures
  teps/0050-ignore-task-failures.md
  teps/README.md
  teps/images/0050-jenkins-dashboard-with-failure-stage.png
  teps/images/0050-jenkins-dashboard-with-unstable-stage.png
  teps/images/0050-jenkins-dashboard.png
Labels: approved, kind/tep, lgtm, size/L

#373 Add sbwsg for lgtm on results PRs
  org/org.yaml
Labels: approved, lgtm, size/XS

#364 Add sbwsg as owner on community repo
  OWNERS
Labels: approved, lgtm, size/XS

#370 Update self-reference from master to main 🧙
  design-principles.md
  governance.md
  process.md
  standards.md
  teps/0001-tekton-enhancement-proposal-process.md
  teps/0020-s390x-support.md
  teps/0024-embedded-trigger-templates.md
  teps/0040-ignore-step-errors.md
  teps/0045-whenexpressions-in-finally-tasks.md
  teps/0051-ppc64le-architecture-support.md
  teps/README.md
  teps/README.md.mustache
Labels: approved, lgtm, size/M

#375 Add spikeburton to catalog collaborators
  org/org.yaml
Labels: approved, lgtm, size/XS

#377 Fix the org README
  org/README.md
Labels: approved, lgtm, size/XS

#378 Add Jordan (Tao Zhang) to the Tekton org
  org/org.yaml
Labels: approved, lgtm, size/XS

#376 adding sbose78 to the org
  org/org.yaml
Labels: approved, lgtm, size/XS

#338 Update experimental reference from master to main 🧙
  teps/0005-tekton-oci-bundles.md
  teps/0021-results-api.md
Labels: approved, kind/misc, lgtm, size/XS

#379 Create a team of doc reviewers
  org/org.yaml
Labels: approved, lgtm, size/S

#335 Update triggers reference from master to main 🧙
  roadmap.md
  teps/0002-custom-tasks.md
  teps/0008-support-knative-service-for-triggers-eventlistener-pod.md
  teps/0022-trigger-immutable-input.md
  teps/0026-interceptor-plugins.md
  teps/0035-document-tekton-position-around-policy-authentication-authorization.md
Labels: approved, kind/misc, lgtm, size/S

#381 Add fenglixa as member
  org/org.yaml
Labels: approved, lgtm, size/XS

#334 Update cli reference from master to main 🧙
  roadmap.md
Labels: approved, kind/misc, lgtm, size/XS

#319 TEP-0047: Pipeline Task Display Name
  teps/0047-pipeline-task-display-name.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#316 Add TEP-0044: Decouple Task Composition from Scheduling ➰
  teps/0044-decouple-task-composition-from-scheduling.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/XXL

#308 Add TEP-0042 TaskRun breakpoint on failure
  teps/0042-taskrun-breakpoint-on-failure.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#332 Update pipeline reference from master to main 🧙
  roadmap.md
  standards.md
  teps/0001-tekton-enhancement-proposal-process.md
  teps/0007-conditions-beta.md
  teps/0021-results-api.md
  teps/0024-embedded-trigger-templates.md
  teps/0028-task-execution-status-at-runtime.md
  teps/0029-step-workspaces.md
  teps/0030-workspace-paths.md
  teps/0035-document-tekton-position-around-policy-authentication-authorization.md
  teps/0037-remove-gcs-fetcher.md
  teps/0045-whenexpressions-in-finally-tasks.md
  user-profiles.md
Labels: approved, kind/misc, lgtm, size/L

#357 TEP-0052: Update proposal to be less etcd/performance focused.
  teps/0052-tekton-results-automated-run-resource-cleanup.md
  teps/README.md
  teps/images/0052-k8sapi.png
  teps/images/0052-sharedinformer.png
Labels: approved, kind/tep, lgtm, size/L

#387 TEP-0052: Automated RunResource Cleanup - Mark proposal as implementable
  teps/0052-tekton-results-automated-run-resource-cleanup.md
  teps/README.md
Labels: approved, lgtm, size/XS

#385 update: tep-0042 user stories and alternatives
  teps/0042-taskrun-breakpoint-on-failure.md
Labels: approved, kind/tep, lgtm

#391 Add briangleeson to Dashboard collaborators
  org/org.yaml
Labels: approved, lgtm, size/XS

#392 Mark 0031 as implemented
  teps/0031-tekton-bundles-cli.md
  teps/README.md
Labels: approved, lgtm, size/S

#384 TEP-0058: Graceful Pipeline Run Termination
  teps/0058-graceful-pipeline-run-termination.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#395 Add table demonstrating flags and fix typos 🛠️
  teps/0033-tekton-feature-gates.md
Labels: approved, lgtm, size/S

#396 add jerop and pritidesai to teps/OWNERS
  teps/OWNERS
Labels: approved, lgtm, size/XS
