Repository tektoncd/community, pull requests merged in 2021-07, with the labels that each got.

#470 fix: readme anchor
  README.md
Labels: approved, lgtm, size/XS

#471 Add sm43 as collaborator on operator
  org/org.yaml
Labels: approved, lgtm, size/XS

#472 Add shaowenchen to the org
  org/org.yaml
Labels: approved, lgtm, size/XS

#461 TEP-0071: Custom Task SDK.
  teps/0071-custom-task-sdk.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#440 Add Alternatives for Remote Resource Resolution TEP
  teps/0060-remote-resource-resolution.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/XL

#463 proposal for TEP 0040 - ignore step error with a new section `exit`
  teps/0040-ignore-step-errors.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#428 TEP-0072: Results: JSON Serialized Records [proposed]
  teps/0072-results-json-serialized-records.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#476 Fix my Slack display name
  governance.md
Labels: approved, lgtm, size/XS

#473 Update CLI maintainers 👻
  org/org.yaml
Labels: approved, lgtm, size/XS

#474 TEP-0040 - minor corrections
  teps/0040-ignore-step-errors.md
Labels: approved, kind/tep, lgtm, size/XS

#478 [TEP-0050] Clarify impact on overall pipeline status 📜
  teps/0050-ignore-task-failures.md
Labels: approved, kind/tep, lgtm, size/S

#482 Fix link for triggers working group notes 🔗
  working-groups.md
Labels: approved, lgtm, size/XS

#483 Remove @chhsia0 from facilitator list for now ❤️
  working-groups.md
Labels: approved, lgtm, size/XS

#485 Add frerikandriessen to the org
  org/org.yaml
Labels: approved, lgtm, size/XS

#486 org: remove duplicated names from cli.collaborators
  org/org.yaml
Labels: approved, lgtm, size/XS

#487 org: remove duplicated names from cli.maintainers
  org/org.yaml
Labels: approved, lgtm, size/XS

#475 TEP-0023: Implicit Params - mark as implementable.
  teps/0023-implicit-mapping.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/M

#441 TEP-0069: Support retries for custom task in a pipeline.
  teps/0069-support-retries-for-custom-task-in-a-pipeline.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#489 Add @vinamra28 as CLI WG facilitator
  working-groups.md
Labels: approved, lgtm, size/XS
