Repository tektoncd/community, pull requests merged in 2021-10, with the labels that each got.

#524 fixing the meet link for chains WG
  working-groups.md
Labels: size/XS, lgtm, approved

#522 adding pritidesai as chains collaborator
  org/org.yaml
Labels: size/XS, lgtm, approved

#525 Add loosebazooka as chains collaborator
  org/org.yaml
Labels: size/XS, lgtm, approved

#526 Adding an hacktoberfest 2021 page
  README.md
  hacktoberfest-2021.md
Labels: size/M, lgtm, approved

#527 TEP-0080 Example syntax with enclosing single/double quotes
  teps/0080-support-domainscoped-parameterresult-names.md
Labels: lgtm, approved, size/S, kind/tep
