Repository tektoncd/community, pull requests merged in 2021-12, with the labels that each got.

#568 Update alternate WG facilitator rotation
  working-groups.md
Labels: size/XS, lgtm, approved, kind/misc

#571 Sync operator teams organization
  org/org.yaml
Labels: size/XS, lgtm, approved

#567 [Problem Statement] TEP-0096: Pipelines V1 Release
  teps/0096-pipelines-v1-api.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep

#566 TEP 0042 Update: Mark as implemented
  teps/0042-taskrun-breakpoint-on-failure.md
  teps/README.md
Labels: size/XS, lgtm, approved, kind/tep

#574 TEP-0014: Step Timeout - mark as implemented
  teps/0014-step-timeout.md
  teps/README.md
Labels: size/XS, lgtm, approved

#547 TEP-0060: Update proposal and mark Remote Resolution implementable
  teps/0060-remote-resource-resolution.md
  teps/README.md
Labels: lgtm, approved, size/XXL, kind/tep

#576 [TEP-0012]: Mark as implemented
  teps/0012-api-spec.md
  teps/README.md
Labels: lgtm, approved, size/S, kind/tep

#577 TEP-0046: Mark as implemented
  teps/0046-finallytask-execution-post-timeout.md
  teps/README.md
Labels: lgtm, approved, size/S

#578 Add governing board / community meeting 👩‍⚖️
  working-groups.md
Labels: lgtm, approved, size/S

#581 TEP-0023: Mark as implemented
  teps/0023-implicit-mapping.md
  teps/README.md
Labels: size/XS, lgtm, approved

#582 TEP-0002: Mark as implemented
  teps/0002-custom-tasks.md
  teps/README.md
Labels: size/XS, lgtm, approved

#580 TEP-0058: Mark as implemented
  teps/0058-graceful-pipeline-run-termination.md
  teps/README.md
Labels: size/XS, lgtm, approved

#584 TEP-0033: Mark as implemented
  teps/0033-tekton-feature-gates.md
  teps/README.md
Labels: size/XS, lgtm, approved

#585 TEP-0062: Mark as implemented
  teps/0062-catalog-tags-and-hub-categories-management.md
  teps/README.md
Labels: size/XS, lgtm, approved

#563 Added myself to org
  org/org.yaml
Labels: size/XS, lgtm, approved

#573 [TEP-0096]: Pipelines V1 Scope
  teps/0096-pipelines-v1-api.md
  teps/README.md
Labels: size/M, lgtm, approved, kind/tep

#579 TEP-0069: Mark as implemented
  teps/0069-support-retries-for-custom-task-in-a-pipeline.md
  teps/README.md
Labels: size/XS, lgtm, approved

#590 Add sbwsg as collaborator in plumbing
  org/org.yaml
Labels: size/XS, lgtm, approved

#589 Add chuangw6 to org
  org/org.yaml
Labels: size/XS, lgtm, approved
