Repository tektoncd/community, pull requests merged in 2021-06, with the labels that each got.

#352 TEP- 0067 Tekton Catalog Pipeline Organization
  teps/0067-tekton-catalog-pipeline-organization.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#445 Update that tekton-users can now have read access to the drive
  contact.md
Labels: approved, lgtm, size/XS

#449 TEP-0045: WhenExpressions in Finally Tasks - Mark as Implemented
  teps/0045-whenexpressions-in-finally-tasks.md
  teps/README.md
Labels: approved, kind/cleanup, lgtm, size/XS

#450 TEP-0004: Task Results in Final Tasks - Mark as Implemented
  teps/0004-task-results-in-final-tasks.md
  teps/README.md
Labels: approved, kind/cleanup, lgtm, size/XS

#451 TEP-0028: Task Execution Status at Runtime - Mark as Implemented
  teps/0028-task-execution-status-at-runtime.md
  teps/README.md
Labels: approved, kind/cleanup, lgtm, size/XS

#452 TEP-0049: Aggregate Status of DAG Tasks - Mark as Implemented
  teps/0049-aggregate-status-of-dag-tasks.md
  teps/README.md
Labels: approved, kind/cleanup, lgtm, size/XS

#453 Add details about Chains WG to working-groups doc
  working-groups.md
Labels: approved, lgtm, size/S

#454 TEP-0020: s390x architecture support - Mark as Implemented
  teps/0020-s390x-support.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/XS

#456 Add pull-request template 🙃
  .github/PULL_REQUEST_TEMPLATE/free-form.md
  .github/PULL_REQUEST_TEMPLATE/tep.md
Labels: approved, lgtm, size/S

#448 TEP-0007: Conditions Beta - Mark as Implemented
  teps/0007-conditions-beta.md
  teps/README.md
Labels: approved, kind/cleanup, lgtm, size/M

#427 TEP-0066 Tekton Dogfooding
  teps/0066-dogfooding-tekton.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#460 Add myself
  org/org.yaml
Labels: approved, lgtm, size/XS

#462 Add waveywaves as experimental collaborator
  org/org.yaml
Labels: approved, lgtm, size/XS

#443 TEP-0070: Platform support in Tekton catalog
  teps/0070-tekton-catalog-task-platform-support.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#458 Update Catalog Tags and Hub Category Management TEP status
  teps/0062-catalog-tags-and-hub-categories-management.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/XS

#433 Update the TEP-2 to newly proposed timeout implementation.
  teps/0002-custom-tasks.md
Labels: approved, kind/tep, lgtm, size/S

#469 Updates minor change in annotation
  teps/0062-catalog-tags-and-hub-categories-management.md
Labels: approved, lgtm, size/XS

#467 Add briangleeson to the dashboard.maintainers team
  org/org.yaml
Labels: approved, lgtm, size/XS
