Repository tektoncd/community, pull requests merged in 2021-05, with the labels that each got.

#415 TEP-0061 Allow custom task to be embedded in pipeline, design.
  teps/0061-allow-custom-task-to-be-embedded-in-pipeline.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/M

#423 Add priyawadhwa@ to the org and as a chains maintainer
  org/org.yaml
Labels: approved, lgtm, size/XS

#424 Fix the org file
  org/org.yaml
Labels: approved, lgtm, size/XS

#397 TEP-0058 Graceful Pipeline Run Termination - design details
  teps/0058-graceful-pipeline-run-termination.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#400 TEP-0062 Catalog Tags and Hub Categories Management
  teps/0062-catalog-tags-and-hub-categories-management.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#389 TEP-0060: Remote Resource Resolution
  teps/0060-remote-resource-resolution.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#407 TEP-0059: Skipping Strategies
  teps/0059-skip-guarded-task-only.md
  teps/0059-skipping-strategies.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/XXL

#329 TEP-0041: Add TEP for Tekton Component Versioning
  teps/0041-tekton-component-versioning.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#430 add LyndseyBu as member and dashboard collaborator
  org/org.yaml
Labels: approved, lgtm, size/XS

#436 Add sbwsg for lgtm to experimental collaborators
  org/org.yaml
Labels: approved, lgtm, size/XS

#431 adding mrutkows to the org
  org/org.yaml
Labels: approved, lgtm, size/XS

#434 Add myself to the ORG !
  org/org.yaml
Labels: approved, lgtm, size/XS

#438 fix: readme desc
  roadmap.md
Labels: approved, lgtm, size/XS

#439 improvement: redirect link
  code-of-conduct.md
Labels: approved, lgtm, size/XS

#432 Update the TEP-61 to implemented
  teps/0061-allow-custom-task-to-be-embedded-in-pipeline.md
  teps/README.md
Labels: approved, lgtm, size/M
