Repository tektoncd/community, pull requests merged in 2021-02, with the labels that each got.

#328 Adding myself to the catalog.maintainers list
  org/org.yaml
Labels: approved, lgtm, size/XS

#339 Update plumbing reference from master to main 🧙
  governance.md
  org/README.md
  standards.md
Labels: approved, kind/misc, lgtm, size/XS

#239 TEP-0039 Add Variable `retries` and `retry-count`
  teps/0039-add-variable-retries-and-retrycount.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#336 Update website reference from master to main 🧙
  standards.md
Labels: approved, kind/misc, lgtm, size/XS

#280 TEP-0033 Tekton Feature Gates
  teps/0033-tekton-feature-gates.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#344 Add the collaborators role to the community docs
  process.md
Labels: approved, lgtm, size/M

#343 Update Catalog Org TEP for Version Bump condition
  teps/0003-tekton-catalog-organization.md
  teps/README.md
Labels: approved, lgtm, size/S

#322 TEP-0051 : Add ppc64le architecture support
  teps/0051-ppc64le-architecture-support.md
  teps/README.md
  teps/images/0051-diagram.jpg
Labels: approved, kind/tep, lgtm, size/L

#347 TEP-0052: Tekton Results: Automated Run Resource Cleanup
  teps/0052-tekton-results-automated-run-resource-cleanup.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#354 Update Jason's corporate affiliation
  governance.md
Labels: approved, lgtm, size/XS

#351 Add @rudeigerc to the org
  org/org.yaml
Labels: approved, lgtm, size/XS

#302 TEP-0040 - ignore step error
  teps/0040-ignore-step-errors.md
  teps/README.md
Labels: approved, kind/tep, lgtm, size/L

#356 Update roadmap for 2021! 🛣️
  roadmap.md
Labels: approved, lgtm, size/M
