Repository tektoncd/community, pull requests merged in 2022-03, with the labels that each got.

#644 Fix link to contributor ladder from main README 🔗
  README.md
Labels: size/XS, lgtm, approved

#642 Add @khrm @savitaashture as experimental collaborators
  org/org.yaml
Labels: size/XS, lgtm, approved

#646 Add Yongxuanzhang to experimental collaborators members
  org/org.yaml
Labels: size/XS, lgtm, approved

#649 Update tekton governance team
  org/org.yaml
Labels: size/XS, lgtm, approved

#648 Update the experimental maintainers
  org/org.yaml
Labels: size/XS, lgtm, approved

#651 Add wlynch to chains.collaborators
  org/org.yaml
Labels: size/XS, lgtm, approved

#626 TEP-0048 - Update `Results` TEP to add use case of Providing Default Values
  teps/0048-task-results-without-results.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep

#641 [TEP-0074]: Not a V1 blocker
  teps/0074-deprecate-pipelineresources.md
  teps/README.md
Labels: lgtm, approved, size/S, kind/tep

#640 [TEP-0096]: Remove TEP-0074 Features as blockers
  teps/0096-pipelines-v1-api.md
Labels: size/XS, lgtm, approved, kind/tep

#639 Change status of TEP0073 to implemented
  teps/0073-simplify-metrics.md
  teps/README.md
Labels: size/XS, lgtm, approved, kind/tep

#652 [TEP-0044]: Propose pipeline in pod + rollout plan
  teps/0044-data-locality-and-pod-overhead-in-pipelines.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep

#657 Update gov board with new members
  governance.md
Labels: lgtm, approved, size/S

#659 [TEP-0096]: Update to implementable
  teps/0096-pipelines-v1-api.md
  teps/README.md
Labels: size/XS, lgtm, approved, kind/tep

#645 [TEP-0100] Update to handle PipelineTask condition checks and when expressions
  teps/0100-embedded-taskruns-and-runs-status-in-pipelineruns.md
  teps/README.md
Labels: size/M, lgtm, approved, kind/tep

#653 Add a leave policy for governing board members 🏖️
  governance.md
Labels: lgtm, approved, size/S

#666 Add priyawadhwa as community collaborator
  org/org.yaml
Labels: size/XS, lgtm, approved
