Repository tektoncd/community, pull requests merged in 2022-10, with the labels that each got.

#838 [TEP-0115] Support git-based versioning validation in Catlin
  teps/0115-tekton-catalog-git-based-versioning.md
  teps/README.md
Labels: lgtm, approved, size/S, kind/tep

#845 Add lbernick to experimental collaborators
  org/org.yaml
Labels: size/XS, lgtm, approved

#669 Create a community.maintainers team
  org/org.yaml
Labels: lgtm, approved, size/S, lifecycle/stale

#843 Add initial adopters file
  README.md
  adopters.md
Labels: size/M, lgtm, approved

#850 Update adopters to include FRSCA
  adopters.md
Labels: size/XS, lgtm, approved

#847 TEP-0120: Add link to experimental + extra use case
  teps/0120-canceling-concurrent-pipelineruns.md
Labels: size/XS, lgtm, approved, kind/tep

#848 Add VSCode and JetBrains IDEs tooling
  adopters.md
Labels: size/XS, lgtm, approved

#853 Update adopters.md
  adopters.md
Labels: size/XS, lgtm, approved

#852 Adds piyush-garg as operator maintainer
  org/org.yaml
Labels: size/XS, lgtm, approved

#854 Add RafaeLeal to org + experimental collaborators
  org/org.yaml
Labels: size/XS, lgtm, approved

#855 @jerop hands back governing board seat to @bobcatfish
  OWNERS
  governance.md
  org/org.yaml
Labels: lgtm, approved, size/S

#849 Adding Approval Tasks for Tekton based on Automatiko
  adopters.md
Labels: size/XS, lgtm, approved

#857 Add alan-ghelardi to org
  org/org.yaml
Labels: size/XS, lgtm, approved

#860 add parth (pxp928) to tekton org
  org/org.yaml
Labels: size/XS, lgtm, approved

#841 org: update with recent catalog/pipeline owner updates
  org/org.yaml
Labels: size/XS, lgtm, approved

#842 [TEP-0115] Update Artifact Hub Usage
  teps/0115-tekton-catalog-git-based-versioning.md
  teps/README.md
  teps/images/0115-artifacthub-versioning.png
Labels: lgtm, approved, size/L, kind/tep

#861 Add Google to Vendors table
  adopters.md
Labels: size/XS, lgtm, approved

#862 TEP-0114: Custom Tasks Beta - Retries
  teps/0114-custom-tasks-beta.md
  teps/README.md
Labels: lgtm, approved, size/S, kind/tep

#859 [TEP-0079] Ownership and Maintenance
  teps/0079-tekton-catalog-support-tiers.md
  teps/README.md
Labels: lgtm, approved, size/XL, kind/tep

#864 [TEP-0060] Mark as implemented
  teps/0060-remote-resource-resolution.md
  teps/README.md
Labels: lgtm, approved, size/S, kind/tep

#865 Add chuangw6 to chains collaborators.
  org/org.yaml
Labels: size/XS, lgtm, approved

#863 TEP-0117: Mark `implementable`
  teps/0117-tekton-results-logs.md
  teps/README.md
Labels: size/XS, lgtm, approved

#856 Clarify LTS, support and number of releases
  releases.md
Labels: size/M, lgtm, approved
