Repository tektoncd/community, pull requests merged in 2022-12, with the labels that each got.

#884 governance.md: fix a type in my name
  governance.md
Labels: size/XS, lgtm, approved

#837 Add security design requirements to Tekton
  design-principles.md
Labels: lgtm, approved, size/S

#885 [TEP-0079] Verified Catalogs & Trusted Resource Integration
  teps/0079-tekton-catalog-support-tiers.md
  teps/README.md
  teps/images/0079-signed-badge.png
Labels: size/M, lgtm, approved, kind/tep

#830 [TEP-0091] Update TEP with design evaluations and more examples
  teps/0091-trusted-resources.md
Labels: lgtm, approved, size/L, kind/tep

#799 [TEP-0086] Update PVC/workspace result passing POC
  teps/0086-changing-the-way-result-parameters-are-stored.md
Labels: size/M, lgtm, approved

#887 TEP-0127: Larger Results via Sidecar Logs
  teps/0127-larger-results-via-sidecar-logs.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep

#820 TEP-0122 complete build instructions and parameters
  teps/0122-complete-build-instructions-and-parameters.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep

#875 Avoid feature flags that change behavior of tasks/pipelines.
  design-principles.md
Labels: size/XS, lgtm, approved

#895 Add Nubank as one of the Tekton adopters
  adopters.md
Labels: size/XS, lgtm, approved

#891 TEP-0121: Add status transition details
  teps/0121-refine-retries-for-taskruns-and-customruns.md
  teps/README.md
Labels: size/M, lgtm, approved

#896 TEP-0114: Custom Tasks Beta - Mark as Implemented
  teps/0114-custom-tasks-beta.md
  teps/README.md
Labels: lgtm, approved, size/S

#899 Add new pipeline reviewers - chuangw6, Yongxuanzhang
  org/org.yaml
Labels: size/XS, lgtm, approved

#901 [TEP-0115] Mark TEP-0115 as Implemented
  teps/0115-tekton-catalog-git-based-versioning.md
  teps/README.md
Labels: lgtm, approved, size/S

#890 TEP-0101: Mark as implementable.
  teps/0101-env-in-pod-template.md
  teps/README.md
Labels: size/XS, lgtm, approved

#902 TEP-0127: Larger Results via Sidecar Logs - Mark as Implemented
  teps/0127-larger-results-via-sidecar-logs.md
  teps/README.md
Labels: lgtm, approved, size/S

#906 Fix ./hack/update-toc.sh
  hack/update-toc.sh
  teps/0029-step-workspaces.md
  teps/0044-data-locality-and-pod-overhead-in-pipelines.md
  teps/0048-task-results-without-results.md
  teps/0056-pipelines-in-pipelines.md
  teps/0075-object-param-and-result-types.md
  teps/0076-array-result-types.md
  teps/0079-tekton-catalog-support-tiers.md
  teps/0081-add-chains-subcommand-to-the-cli.md
  teps/0084-endtoend-provenance-collection.md
  teps/0086-changing-the-way-result-parameters-are-stored.md
  teps/0091-trusted-resources.md
  teps/0092-scheduling-timeout.md
  teps/0093-add-sign-verify-subcommand-to-the-cli.md
  teps/0094-configuring-resources-at-runtime.md
  teps/0095-common-repository-configuration.md
  teps/0096-pipelines-v1.md
  teps/0097-breakpoints-for-taskruns-and-pipelineruns.md
  teps/0098-workflows.md
  teps/0101-env-in-pod-template.md
  teps/0104-tasklevel-resource-requirements.md
  teps/0105-remove-pipeline-v1alpha1-api.md
  teps/0106-support-specifying-metadata-per-task-in-runtime.md
  teps/0109-better-structured-provenance-retrieval-in-tekton-chains.md
  teps/0111-propagating-workspaces.md
  teps/0112-replace-volumes-with-workspaces.md
  teps/0114-custom-tasks-beta.md
  teps/0115-tekton-catalog-git-based-versioning.md
  teps/0116-referencing-finally-task-results-in-pipeline-results.md
  teps/0118-matrix-with-explicit-combinations-of-parameters.md
  teps/0119-add-taskrun-template-in-pipelinerun.md
  teps/0120-canceling-concurrent-pipelineruns.md
  teps/0121-refine-retries-for-taskruns-and-customruns.md
  teps/0122-complete-build-instructions-and-parameters.md
  teps/0125-add-credential-filter-to-entrypoint-logger.md
Labels: lgtm, approved, kind/cleanup, size/XL

#905 Mark TEP-0121 As Implemented
  teps/0121-refine-retries-for-taskruns-and-customruns.md
  teps/README.md
Labels: size/M, lgtm, approved

#907 [TEP-0009] Mark as implemented
  teps/0009-trigger-crd.md
  teps/README.md
Labels: size/XS, lgtm, approved, kind/tep

#910 TEP-0101 Mark as implemented.
  teps/0101-env-in-pod-template.md
  teps/README.md
Labels: size/XS, lgtm, approved

#908 Add Go style guide to community standards
  standards.md
Labels: size/XS, lgtm, approved

#898 Add @alan-ghelardi as a Results collaborator/reviewer
  org/org.yaml
Labels: size/XS, lgtm, approved
