Repository tektoncd/community, pull requests merged in 2023-07, with the labels that each got.

#893 Tekton Results Working Group
  working-groups.md
Labels: lgtm, approved, size/S

#1033 Add ywluogg into golang verified catalogs' collaborators and as tektoncd-catalog org member
  org/org.yaml
Labels: size/XS, lgtm, approved

#1028 [TEP-0137] CloudEvents controller
  teps/0137-cloudevents-controller.md
  teps/README.md
Labels: lgtm, approved, size/XL, kind/tep

#928 Add matrix beta to roadmap
  roadmap.md
Labels: size/XS, lgtm, approved

#1024 [TEP-0091] add implemention PRs for milestones
  teps/0091-trusted-resources.md
  teps/README.md
Labels: size/M, lgtm, approved

#1038 Add lcarva to plumbing.collaborators
  org/org.yaml
Labels: size/XS, lgtm, approved

#1040 Add chuangw6 to chains maintainers.
  org/org.yaml
Labels: size/XS, lgtm, approved

#1039 Make chitrangpatel a Chains maintainer
  org/org.yaml
Labels: size/XS, lgtm, approved

#1042 [TEP-0138] Decouple API and Feature Versioning Problem Statement
  teps/0138-decouple-api-and-feature-versioning.md
  teps/README.md
Labels: size/M, lgtm, approved

#1041 [TEP-0136] Mark as implementable
  teps/0136-capture-traces-for-task-pod-events.md
  teps/README.md
Labels: size/M, lgtm, approved, kind/tep
