Repository tektoncd/community, pull requests merged in 2023-10, with the labels that each got.

#1034 [TEP-0138]: Decouple API and Feature Versioning Proposal
  teps/0033-tekton-feature-gates.md
  teps/0138-decouple-api-and-feature-versioning.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep

#1079 Add QuanZhang-William to Pipeline Reviewer
  org/org.yaml
Labels: size/XS, lgtm, approved

#1082 Add @yongxuanzhang and @wlynch to core.maintainers
  org/org.yaml
Labels: size/XS, lgtm, approved

#1085 Add @chitrangpatel to core.maintainers team
  org/org.yaml
Labels: size/XS, lgtm, approved, kind/misc

#1074 [TEP-0145] CEL in WhenExpression
  teps/0145-cel-in-whenexpression.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep

#1088 Add chitrang as community collaborator
  org/org.yaml
Labels: size/XS, lgtm, approved

#1090 Update the Docs WG time
  working-groups.md
Labels: size/XS, lgtm, approved

#1065 [TEP-0142] Enable Step Reusability
  teps/0142-enable-step-reusability.md
  teps/README.md
  teps/images/0142-clone-build-push-pipeline.png
  teps/images/0142-clone-build-push-task.png
  teps/images/0142-components.png
  teps/images/0142-multi-node-workspace-overhead.png
  teps/images/0142-pod-overhead.png
  teps/images/0142-workspace-overhead.png
Labels: lgtm, approved, size/XXL, kind/tep

#1072 [TEP-0144] Param Enum
  teps/0144-param-enum.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep

#1094 Use non expiring Slack invite link
  contact.md
Labels: size/XS, lgtm, approved

#1095 [TEP-140] Mark TEP-140 As Implemented
  teps/0140-producing-results-in-matrix.md
  teps/README.md
Labels: size/XS, lgtm, approved

#1096 [TEP 140] Add Implementation Reference
  teps/0140-producing-results-in-matrix.md
Labels: size/XS, lgtm, approved

#1100 Add sayan, avinal and Emil (Result Maintainer) to Community
  org/org.yaml
Labels: size/XS, lgtm, approved
