Repository tektoncd/community, pull requests merged in 2023-06, with the labels that each got.

#1023 Update operator's owners to be in sync with the repository
  org/org.yaml
Labels: lgtm, approved, size/S

#1018 Fix broken Docs links in standards.md
  standards.md
Labels: size/XS, lgtm, approved

#1025 TEP-0135: update coscheduling default value
  teps/0135-coscheduling-pipelinerun-pods.md
  teps/README.md
Labels: size/M, lgtm, approved, kind/tep

#1027 Add OneStock to the list of end users
  adopters.md
Labels: size/XS, lgtm, approved

#1031 [TEP-0135] Rename coscheduling feature flag values
  teps/0135-coscheduling-pipelinerun-pods.md
  teps/README.md
Labels: size/M, lgtm, approved, kind/tep
