Repository tektoncd/community, pull requests merged in 2023-05, with the labels that each got.

#1009 Cleanup org.yaml for chains groups.
  org/org.yaml
Labels: lgtm, approved, size/S

#937 Update chains WG facilitator list to point to WG doc.
  working-groups.md
Labels: lgtm, approved, size/S

#1015 TEP-0134: Concise Pipelines - Problem Statement
  teps/0134-concise-pipelines.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep

#1017 TEP-0135: Coscheduling PipelineRun pods
  teps/0135-coscheduling-pipelinerun-pods.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep

#1008 Include authorship of pull requests in ladder requirements
  process/contributor-ladder.md
Labels: size/XS, lgtm, approved

#1020 Use `%w` to wrap errors.
  standards.md
Labels: size/XS, lgtm, approved
