Repository tektoncd/community, pull requests merged in 2023-02, with the labels that each got.

#931 [Code standards] Add detail on small PRs and Go packages
  standards.md
Labels: lgtm, approved, size/L

#946 [TEP-0008]: Mark as implemented and update TOCs
  teps/0008-support-knative-service-for-triggers-eventlistener-pod.md
  teps/0021-results-api.md
  teps/0074-deprecate-pipelineresources.md
  teps/0098-workflows.md
  teps/README.md
Labels: size/M, lgtm, approved, kind/tep

#932 Refactor process documentation
  README.md
  process.md
  process/README.md
  process/contributor-ladder.md
  process/projects.md
  process/tep-process.md
  teps/README.md
  teps/README.md.mustache
Labels: lgtm, approved, size/XXL

#923 [TEP-0129] Multiple Tekton instances per Cluster
  teps/0129-multiple-tekton-instances-per-cluster.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep

#952 Add jkandasa to the org
  org/org.yaml
Labels: size/XS, lgtm, approved

#940 [TEP-0074] Update plans for image support
  teps/0074-deprecate-pipelineresources.md
Labels: size/M, lgtm, approved, kind/tep

#962 Update the CLI and Operator WG meeting time
  working-groups.md
Labels: size/M, lgtm, approved

#967 TEP-0122: Mask as Implemented
  teps/0122-complete-build-instructions-and-parameters.md
  teps/README.md
Labels: lgtm, approved, size/S
