Repository tektoncd/community, pull requests merged in 2023-11, with the labels that each got.

#1077 [TEP-0146] `Parameters` in `Script`
  teps/0146-parameters-in-script.md
  teps/README.md
Labels: lgtm, approved, size/XL, kind/tep

#1102 Add Chitrang to TEP owners to grant approval privileges
  teps/OWNERS
Labels: size/XS, lgtm, approved

#1103 Add Yongxuanzhang to community collaborators
  org/org.yaml
Labels: size/XS, lgtm, approved

#1071 [TEP-0143] Concise Parameters and Results - proposed
  teps/0143-concise-parameters-results.md
  teps/README.md
Labels: lgtm, approved, size/XL, kind/tep

#1104 remove loosebazooka
  org/org.yaml
Labels: size/XS, lgtm, approved

#1105 OWNERS: s/bobcatfish/jerop
  OWNERS
Labels: size/XS, lgtm, approved

#1106 [TEP-0144] Param Subset Enforcement
  teps/0144-param-enum.md
  teps/README.md
Labels: lgtm, approved, size/S, kind/tep

#1107 Update usage of StepResults with StepActions
  teps/0142-enable-step-reusability.md
  teps/README.md
Labels: size/M, lgtm, approved

#1109 Allianz Direct becomes Tekton End User
  adopters.md
Labels: lgtm, approved, size/S

#1110 Add CloudBees as Tekton vendor
  adopters.md
Labels: size/XS, lgtm, approved

#1115 Add QuanZhang-William to Catlin Reviewer
  org/org.yaml
Labels: size/XS, lgtm, approved, kind/misc

#1114 [TEP-0144] Implemented
  teps/0144-param-enum.md
  teps/README.md
Labels: size/XS, lgtm, approved, kind/tep

#1116 Add JeromeJu as a pipelines maintainer
  org/org.yaml
Labels: size/XS, lgtm, approved
