Repository tektoncd/community, pull requests merged in 2023-09, with the labels that each got.

#1060 Add jisoolee to the Tekton org
  org/org.yaml
Labels: size/XS, lgtm, approved

#1063 Add Avinal to Results Collaborator/Maintainer
  org/org.yaml
Labels: size/XS, lgtm, approved, kind/misc

#1046 [TEP-0137] Events as implementable
  teps/0137-cloudevents-controller.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep

#1068 Add vinamra28 as plumbing collaborators
  org/org.yaml
Labels: size/XS, lgtm, approved

#1069 Update Slack invite link
  contact.md
Labels: size/XS, lgtm, approved

#1035 [TEP-0128] Add an alternative Design for Scheduling Pipelineruns
  teps/0128-scheduled-runs.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep
