Repository tektoncd/community, pull requests merged in 2023-08, with the labels that each got.

#1049 Update my tenure on governing board
  governance.md
Labels: size/XS, lgtm, approved

#1043 Add infra repo to plumbing groups permissions
  org/org.yaml
Labels: size/XS, lgtm, approved

#1050 chore: add aaron-prindle to org
  org/org.yaml
Labels: size/XS, lgtm, approved

#1029 [TEP-0129] Add design details, mark as implementable
  teps/0129-multiple-tekton-instances-per-cluster.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep

#1052 chore: add avinal to org
  org/org.yaml
Labels: size/XS, lgtm, approved

#1053 Add adambkaplan to community collaborators
  org/org.yaml
Labels: size/XS, lgtm, approved

#1022 chore: add squakez
  org/org.yaml
Labels: size/XS, lgtm, approved

#1051 Clarify org member requirements.
  process/contributor-ladder.md
Labels: lgtm, approved, size/S

#1058 update Tekton results WG meeting
  working-groups.md
Labels: size/XS, lgtm, approved

#1059 [TEP-0141] Problem statement: Platform context variables
  teps/0141-platform-context-variables.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep
