Repository tektoncd/community, pull requests merged in 2023-01, with the labels that each got.

#916 Clean up TEP TOCs
  teps/0023-implicit-mapping.md
  teps/0062-catalog-tags-and-hub-categories-management.md
  teps/0067-tekton-catalog-pipeline-organization.md
  teps/0070-tekton-catalog-task-platform-support.md
Labels: size/M, lgtm, approved, kind/tep

#911 org: update maintainers team rights to "maintain"
  org/org.yaml
Labels: size/M, lgtm, approved

#913 [TEP-0026]: Mark as implemented
  teps/0026-interceptor-plugins.md
  teps/README.md
Labels: lgtm, approved, size/S, kind/tep

#915 [TEP-0022]: Mark as Implemented
  teps/0022-trigger-immutable-input.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep

#920 Update s3c wg facilitators and details 🎊
  working-groups.md
Labels: lgtm, approved, size/S

#921 Volunteer to facilitate Pipeline and API WG
  working-groups.md
Labels: size/XS, lgtm, approved

#927 [TEP-0102] Mark as implemented
  teps/0102-https-connection-to-triggers-interceptor.md
  teps/README.md
Labels: size/XS, lgtm, approved, kind/tep

#926 [TEP-0039] Mark as implemented
  teps/0039-add-variable-retries-and-retrycount.md
  teps/README.md
Labels: size/XS, lgtm, approved, kind/tep

#925 Add process and template for postmortems
  process.md
Labels: lgtm, approved, size/S

#929 Updated postmortem section
  process.md
Labels: size/XS, lgtm, approved, kind/documentation

#917 Add Jerome and Lee as API WG facilitators
  working-groups.md
Labels: size/M, lgtm, approved

#930 Add EmmaMunley to org
  org/org.yaml
Labels: size/XS, lgtm, approved

#918 Volunteering for Pipeline WG facilitating
  working-groups.md
Labels: size/XS, lgtm, approved

#933 Add tektoncd-catalog org to org.yaml
  org/org.yaml
Labels: size/M, lgtm, approved

#914 [TEP-0079] Catalog Automated Testing and Tekton Dogfooding
  teps/0079-tekton-catalog-support-tiers.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep

#894 TEP0122 - Complete build instructions and parameters - implementable
  teps/0122-complete-build-instructions-and-parameters.md
  teps/README.md
Labels: size/M, lgtm, approved, kind/tep

#922 TEP0074 Update plans to remove `pipelineResources`
  teps/0074-deprecate-pipelineresources.md
Labels: lgtm, approved, size/S, kind/tep

#941 Add XinruZhang as a Pipeline Reviewer
  org/org.yaml
Labels: size/XS, lgtm, approved

#939 Fix working-group format
  working-groups.md
Labels: size/XS, lgtm, approved

#942 Fix the format of working group doc
  working-groups.md
Labels: lgtm, approved, size/S

#944 TEP-0096: Document features that became stable during transition
  teps/0096-pipelines-v1.md
Labels: size/XS, lgtm, approved, kind/tep

#945 Add chengjoey to org
  org/org.yaml
Labels: size/XS, lgtm, approved

#938 Contributing to Milestones
  standards.md
Labels: size/XS, lgtm, approved

#904 [TEP-0128]: Scheduled Runs
  teps/0083-polling-runs-in-tekton.md
  teps/0095-common-repository-configuration.md
  teps/0098-workflows.md
  teps/0128-scheduled-runs.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep

#947 TEP-0124 Mark as implemented
  teps/0124-distributed-tracing-for-tasks-and-pipelines.md
  teps/README.md
Labels: lgtm, approved, size/S, kind/tep

#840 Update TEP 109: align type hinting with other type hinting formating …
  teps/0109-better-structured-provenance-retrieval-in-tekton-chains.md
Labels: lgtm, approved, size/S, kind/tep
