Repository tektoncd/community, pull requests merged in 2024-06, with the labels that each got.

#1151 Request for renzodavid9 to be member of Tekton
  org/org.yaml
Labels: size/XS, lgtm, approved

#1150 Add chitrangpatel to the gov board while dibyom is on leave
  OWNERS
  governance.md
  org/org.yaml
Labels: size/M, lgtm, approved

#1147 TEP-0156 : when-in-steps
  teps/0156-whenexpressions-in-step.md
  teps/README.md
Labels: lgtm, approved, size/L, kind/tep
