Repository tektoncd/community, pull requests merged in 2024-07, with the labels that each got.

#1153 chore: add cugykw to the tektoncd org
  org/org.yaml
Labels: size/XS, lgtm, approved

#1155 Add field `isBuildArtifact` to an artifact category.
  teps/0147-tekton-artifacts-phase1.md
  teps/README.md
Labels: size/M, lgtm, approved, kind/tep

#1159 docs: update tep-0156 status
  teps/0156-whenexpressions-in-step.md
  teps/README.md
Labels: lgtm, approved, size/S
