Repository tektoncd/community, pull requests merged in 2025-09, with the labels that each got.

#1210 Add @infernus01 to tektoncd member
  org/org.yaml
Labels: size/XS, lgtm, approved

#1223 Add jkhelil to chains.maintainers
  org/org.yaml
Labels: size/XS, lgtm, approved, kind/misc

#1225 update operator maintainers
  org/org.yaml
Labels: size/XS, lgtm, approved

#1219 add aThorp96 in core.collaborators
  org/org.yaml
Labels: size/XS, lgtm, approved

#1226 added minor doc fixes
  design-principles.md
  process/contributor-ladder.md
Labels: lgtm, approved, size/S
